---
name: "CITestsClang"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  citests:
    name: CI-Tests-Clang
    runs-on: ubuntu-latest
    env:
        CC: clang
        CXX: clang++
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 2
          submodules: 'recursive'

      - name: Run cmake
        run: |
            sudo apt-get install clangd
            echo $CC
            echo $CXX
            $CC --version
            CXXFLAGS="-Wall -Wextra -Wpedantic -Werror -g"
            CFLAGS="-Wall -Wextra -Wpedantic -Werror -g"
            cmake .
            make -j 4

      - name: Perform Unit Tests
        run: |
            ./ithitest

      - name: Run Valgrind
        run: |
            sudo apt-get install -y valgrind
            valgrind -v --error-exitcode=1  --track-origins=yes ./ithitest
